### ISSUE TITLE
release 0.1.0 RTSP server

### ISSUE THREAD

**Issue by grigoroff** [roleoroleo/yi-hack-6FUS_4.5.0#1]
hi,
many many thanks to you for this great FW !! my 1080p Home cam 6FU with 4.5.0.0B stock FW is flashed and running great ! 
I have active RTSP low-res for testing but when i try to connect with VLC or jeedom(domotic), no video appear.
On SSH i stop an start rRTSPserver and all seems to be good on 554 port.
See attach if i'm doing some thing wrong.
thanks again for huge work 
![adress](https://user-images.githubusercontent.com/11214033/65319184-55f65200-db9f-11e9-9723-230bab60cb3b.png)
![low_res](https://user-images.githubusercontent.com/11214033/65319185-55f65200-db9f-11e9-83b7-36811cf4a10b.png)
![vlc](https://user-images.githubusercontent.com/11214033/65319186-55f65200-db9f-11e9-9b20-a71625d59460.png)

**Comment by roleoroleo** [comment]
Could you please verify if it's work, with cloud enabled?
You can start manually rRTSPServer with an env var to select resolution:
`RRTSP_RES=1 rRTSPServer &`
0: high res
1: low res
2: both

**Comment by grigoroff** [comment]
you right !!! if I enable cloud it works !
any idea why ?

**Comment by roleoroleo** [comment]
I don't know exactly, but if cloud application doesn't start the circular buffer with h264 frames is empty.
To solve this problem system.sh starts cloud application, waits for circular buffer filling and then kills cloud. Something is wrong in this procedure
You could try to increment wait time. From
`while [ "$IDX" -eq "0000" ] && [ $N -lt 50 ]; do`
to
`while [ "$IDX" -eq "0000" ] && [ $N -lt 100 ]; do`

**Comment by roleoroleo** [comment]
I think I solved. The while loop was incorrect.
Please, try release 0.1.1.

**Comment by grigoroff** [comment]
Cool I will see it when I come back! Thanks for your effort

**Comment by JoseFerre** [comment]
Great job @roleoroleo :)
Camera is working fine but rtsp need a active external network connection to start working for first time when restart it, once the stream is up and working I can disable the external network connection without problems.
I will investigate it.
Thank you!!

**Comment by roleoroleo** [comment]
Probably cloud application doesn't start reading if it can't connect to the server.
I will investigate too.
