### ISSUE TITLE
Is this yi-hack also suitable for BFUS variant?

### ISSUE THREAD

**Issue by GarretBlueMango** [roleoroleo/yi-hack-6FUS_4.5.0#14]
I don't know if there's a difference between the 6FUS or BFUS variant of the Yi Dome Camera

**Comment by roleoroleo** [comment]
I don't know.

**Comment by GarretBlueMango** [comment]
Thanks for the fast response. What's the hurt in just trying your tweaked firmware? Can I brick without the possibility of restoring the previous firmware? Or can I always restore the firmware by putting it on an SD. 

Again thanks, for the effort you're putting into this

**Comment by Montaraz1** [comment]
As you already know i flash on 6FUS and BFUS Home Camera. Both successfully.

**Comment by GarretBlueMango** [comment]
@Montaraz1 Sadly I have firmware 4.6.0, so I don't know how to proceed..yet! I'm monitoring other thread about [4.6.0 ](https://github.com/roleoroleo/yi-hack-6FUS_4.5.0/issues/10)
