### ISSUE TITLE
Wifi connection drops often after fw flash

### ISSUE THREAD

**Issue by LIFEPANTS** [roleoroleo/yi-hack-6FUS_4.5.0#16]
After flashing yi-hack-6FUS_4.5.0 0.1.6 the wifi connection to the camera drops out often. A restart of the camera restores connection only to drop out again after some time.

Cameras are mounted in the same location as before flash. The cameras did not show this behaviour before flash.

**Comment by roleoroleo** [comment]
See https://github.com/roleoroleo/yi-hack-6FUS_4.5.0/issues/17
