### ISSUE TITLE
WIFI not reconnecting on reboot

### ISSUE THREAD

**Issue by reptil1990** [roleoroleo/yi-hack-6FUS_4.5.0#17]
The Wifi doesn`t seem to reconnect to the same hotspot after reboot.
Can that be fixed by entering the information in a file via SSH?

**Comment by feiticeir0** [comment]
Have the same problem with the latest version... After a reboot, camera just talks "Waiting to connect"

**Comment by reptil1990** [comment]
Yes same for me!

**Comment by feiticeir0** [comment]
I'm having now the same issue not only with the latest version, but also 0.1.6

**Comment by feiticeir0** [comment]
and 0.1.5... It does not save wifi configurations...

**Comment by roleoroleo** [comment]
Camera model?
Try to enable cloud and re-execute pairing.

**Comment by reptil1990** [comment]
> Camera model?
> Try to enable cloud and re-execute pairing.

Will try later today!

**Comment by feiticeir0** [comment]
> Camera model?
> Try to enable cloud and re-execute pairing.

Will try later.
Yi Home 1080p

**Comment by 22MarioZ** [comment]
Same here. After reboot, camera is waiting for connect. With Yi app I can "successfully" connect to WiFi, but the camera is never shown on network. Also paring with the App is not successful. I have upgrade logs if needed.

**Comment by 22MarioZ** [comment]
I had same problem, not connection to WiFi and loosing the connection after reboot. After couple of retries the camera connected to network and I was able to open web interface. I enable cloud services so that Yi app and camera paired. After that the camera didn't lost WiFi anymore.

**Comment by roleoroleo** [comment]
In the next release I will change the cloud default setting.
So you should be able to repeat pairing.

**Comment by stevekanter** [comment]
I solved this kinda annoyingly but:

1. Factory reset
2. Flashed hacked firmware
3. Connected to wifi from app
4. Went to configuration and disabled Disable Cloud
5. Rebooted
6. Re-connected to wifi and paired fully
7. Re-enabled Disable Cloud

**Comment by GuitarSkater** [comment]
> I solved this kinda annoyingly but:
> 
> 1. Factory reset
> 2. Flashed hacked firmware
> 3. Connected to wifi from app
> 4. Went to configuration and disabled Disable Cloud
> 5. Rebooted
> 6. Re-connected to wifi and paired fully
> 7. Re-enabled Disable Cloud

I tried this about a dozen times, it just times out on the pairing. Any other ideas?

**Comment by stevekanter** [comment]
> > I solved this kinda annoyingly but:
> > 
> > 1. Factory reset
> > 2. Flashed hacked firmware
> > 3. Connected to wifi from app
> > 4. Went to configuration and disabled Disable Cloud
> > 5. Rebooted
> > 6. Re-connected to wifi and paired fully
> > 7. Re-enabled Disable Cloud
> 
> I tried this about a dozen times, it just times out on the pairing. Any other ideas?

Does it successfully read the QR code but just fails to pair? I never experienced THAT. Albeit what I did experience was a hell-of-a-time getting the camera to read the QR code off of my phone. I ended up just sending them to my computer and then the camera read them off the computer no problem. I did this exact set of steps with my 4 different cameras, never a single problem.

**Comment by GuitarSkater** [comment]
Yep, it gets all the way to the successful wifi, I can see it on the net, access the config via browser, it just refuses to pair with the app and times out and reboots. 

I went in and made sure cloud wasn't disabled to no avail. I think I'll just have to wait for the next release

**Comment by roleoroleo** [comment]
Please try 0.1.8.

**Comment by GuitarSkater** [comment]
> Please try 0.1.8.

Can Confirm, Back in action! I also noticed on 1.7 it would periodically reboot, so far that hasnt happened.

Thanks for the great support!!!

**Comment by LouiS22** [comment]
I still notice this with 0.2 and with a Yi 1080 camera.
