### ISSUE TITLE
4.6.0.0A compatibility??

### ISSUE THREAD

**Issue by bepece1** [roleoroleo/yi-hack-6FUS_4.5.0#22]
Is it compatible with 4.6.0.0.A?? 

![](https://user-images.githubusercontent.com/38904049/64078306-6ec6c280-ccd9-11e9-8866-d982953cdf6f.jpeg)

**Comment by roleoroleo** [comment]
Yes.
It's based on this version.

**Comment by bepece1** [comment]
If you install yi-hack-6FUS_4.5.0 into cam, ¿can you continue ussing the original software? 
¿could you came back to original firmware? thankssss
