### ISSUE TITLE
Unable to modify FTP user password

### ISSUE THREAD

**Issue by GuitarSkater** [roleoroleo/yi-hack-6FUS_4.5.0#24]
I was trying to create a password for the FTP access, but when trying to modify the passwd it gives an error that it cannot write to etc/passwd+

Any ideas are welcomed

**Comment by roleoroleo** [comment]
You could try to use pure-ftpd with a different authentication system.
Try this:
https://download.pureftpd.org/pub/pure-ftpd/doc/README.Virtual-Users

**Comment by GuitarSkater** [comment]
I should have specified why I wanted to add a password. I have Home Assists Assistant pull the stills from ftp, it requires a password to be there. As it's currently set to no password, I was just trying add one

**Comment by GuitarSkater** [comment]
This has been addressed and fixed in v.1.8

Thanks!!
