### ISSUE TITLE
Enable RTSP Server?

### ISSUE THREAD

**Issue by Ben-Homeee** [roleoroleo/yi-hack-6FUS_4.5.0#26]
Has the rtsp server to be enabled via a license from discord channel?
If yes, where do I find the cam hash on the yicams interface?
tx

**Comment by roleoroleo** [comment]
RTSP server is GPLv3.
You don't need a license.

**Comment by Ben-Homeee** [comment]
Ok thankyou, i was just wondering because the original yihack needs some kind of licensing
