### ISSUE TITLE
change and Install roleoroleo firmware to yi-hack-v4 cam

### ISSUE THREAD

**Issue by manny199** [roleoroleo/yi-hack-6FUS_4.5.0#27]
Hello, I have a Yi Dome Cloud Camera with yi-hack-v4 firmware.
Is possibile to install new yi-hack-6FUS_4.5.0?

**Comment by roleoroleo** [comment]
No, the hw platform is different.
yi_hack-6FUS is not "new", it's for a different camera.

**Comment by manny199** [comment]
@roleoroleo Hello, thank you for your answer, do you know if there is an alternative firmware with ONVIF for latest Yi Dome Cloud Camera?
I want to buy this model but if there is other camera with ONVIF, mqtt and RTSP i'm very happy

**Comment by roleoroleo** [comment]
I think there are only yi-hack-*.
