### ISSUE TITLE
Update the firmware

### ISSUE THREAD

**Issue by oppinus** [roleoroleo/yi-hack-6FUS_4.5.0#28]
Hi,
can you help me in the update procedure?
Now I've yi-hack-6FUS_4.5.0 0.1.4 on Yi Home 6FUS and works great,  but I would like to update to yi-hack-6FUS-9FUS-BFUS 0.1.9 but I'm not be sure how to do.
Is it the same procedure for apply the hack to a new camera?
Thanks in advance.

**Comment by roleoroleo** [comment]
Yes, is the same procedure.
After the installation you will need to reconfigure the cam.

**Comment by oppinus** [comment]
Ok, perfect.
thank you!
