### ISSUE TITLE
4.5.0.0C firmware

### ISSUE THREAD

**Issue by ivangurin** [roleoroleo/yi-hack-6FUS_4.5.0#8]
It doesn't work on 4.5.0.0C firmware. Could you fix it? Thanks.

**Comment by roleoroleo** [comment]
Did you try it?
Analyzing  4.5.0.0C update there is no reason that it should not work.

**Comment by ivangurin** [comment]
Yes, I did try it. After copy files on flash card, inset flash card to a camera and turn on the camera nothing was happened. The camera hasn't been upgraded to your firmware.  And I don't know why. I am assuming that cause is new official firmware version.

**Comment by roleoroleo** [comment]
It is possible that yi changed the loading procedure.
But unfortunately I can't fix it without having the same fw version.
If you are able to connect a serial cable to the pcb we could analyze the bootlog togheter.

**Comment by ivangurin** [comment]
I'd like to help you, but I don't have serial cable, don't know what is pcb and don't know how to connect cable to camera.

**Comment by Christian-Krupa** [comment]
@roleoroleo i successfully installed your firmware over an 4.5.0.0C_201910... original firmware. rtsp, ssh and webinterface seems to work as expected

**Comment by roleoroleo** [comment]
Good news!
Did you follow a different procedure than the one described in the README?
I would like to understand why @ivangurin didn't succeed.

**Comment by richmidwinter** [comment]
Works for me on 4.5.0.0C_201910080934... at least until I reboot, then I have to go through the pairing process from scratch.

**Comment by roleoroleo** [comment]
And after the pairing it works?

**Comment by ivangurin** [comment]
I still can't upgrade my camera even with new version of firmware. I everything do by instruction. I have 2Gb with fat32, copy files to root, insert card to camera and turn it on. But nothing happens. Camera starts quickly as usual without upgrade. 
On the back of my camera there is qr code with number 6FUSY21KKR. Is firmware suitable for my camera?

**Comment by richmidwinter** [comment]
For me the pairing "fails" as far as the app is concerned but the camera's on the network, services running, I can telnet in, receive the rtsp stream, etc.

And then I reboot and I get the irritating waiting to connect voice message every few seconds and I have to go through the process again.

**Comment by roleoroleo** [comment]
Try to reset the camera and restart the process from scratch.
But before the reset, enable the cloud from the web interface.

**Comment by ivangurin** [comment]
Finally I installed your firmware on my camera. Something was wrong with my sd card. I formatted the sd card from the camera app. After that the firmware was installed successfully. Thank you.
